'use strict';
const express = require('express');
const router = express.Router();
const { authenticate } = require('../middleware/authenticate');
const { authorize } = require('../middleware/authorize');
const { validateBody } = require('../middleware/validate');
const ABMSpecialistController = require('../controllers/abmSpecialist.controller');
const { approveSpecialistSchema, bulkApproveSpecialistSchema, saveSpecialistYearlyTargetsSchema } = require('../validators/specialistSchemas');
router.use(authenticate);
router.use(authorize('abm', 'at_iol_manager', 'eq_mgr_diagnostic', 'eq_mgr_surgical'));
router.get('/specialist-submissions', ABMSpecialistController.getSpecialistSubmissions);
router.put('/approve-specialist/:id', validateBody(approveSpecialistSchema), ABMSpecialistController.approveSpecialist);
router.post('/reject-specialist/:id', ABMSpecialistController.rejectSpecialist);
router.post('/bulk-approve-specialist', validateBody(bulkApproveSpecialistSchema), ABMSpecialistController.bulkApproveSpecialist);
router.get('/specialists', ABMSpecialistController.getSpecialists);
router.get('/unique-specialists', ABMSpecialistController.getUniqueSpecialists);
router.get('/specialist-yearly-targets', ABMSpecialistController.getSpecialistYearlyTargets);
router.post('/specialist-yearly-targets/save', validateBody(saveSpecialistYearlyTargetsSchema), ABMSpecialistController.saveSpecialistYearlyTargets);
router.post('/specialist-yearly-targets/publish', validateBody(saveSpecialistYearlyTargetsSchema), ABMSpecialistController.publishSpecialistYearlyTargets);
router.get('/specialist-dashboard-stats', ABMSpecialistController.getSpecialistDashboardStats);
module.exports = router;
