const express = require('express');
const router = express.Router();
const SalesRepController = require('../controllers/salesrep.controller');
const { authenticate } = require('../middleware/authenticate');
const { authorize } = require('../middleware/authorize');
const { validateBody } = require('../middleware/validate');
const { saveProductSchema, submitMultipleSchema, saveAllProductsSchema } = require('../validators/schemas');
router.use(authenticate);
router.get('/products', authorize('sales_rep', 'tbm', 'abm', 'zbm', 'sales_head'), SalesRepController.getProducts);
router.put('/products/:id/save', authorize('sales_rep', 'tbm'), validateBody(saveProductSchema), SalesRepController.saveProduct);
router.put('/products/:id/targets/:month', authorize('sales_rep', 'tbm'), SalesRepController.updateMonthlyTarget);
router.post('/products/:id/submit', authorize('sales_rep', 'tbm'), SalesRepController.submitProduct);
router.post('/products/submit-multiple', authorize('sales_rep', 'tbm'), validateBody(submitMultipleSchema), SalesRepController.submitMultiple);
router.post('/products/save-all', authorize('sales_rep', 'tbm'), validateBody(saveAllProductsSchema), SalesRepController.saveAll);
router.post('/products/drafts', authorize('sales_rep', 'tbm'), SalesRepController.saveAll);
router.get('/salesrep/dashboard-summary', authorize('sales_rep'), SalesRepController.getDashboardSummary);
router.get('/salesrep/quarterly-summary', authorize('sales_rep'), SalesRepController.getQuarterlySummary);
router.get('/salesrep/category-performance', authorize('sales_rep'), SalesRepController.getCategoryPerformance);
router.put('/products/:id/approve', authorize('tbm', 'abm', 'zbm', 'sales_head'), SalesRepController.approveProduct);
router.put('/products/:id/reject', authorize('tbm', 'abm', 'zbm', 'sales_head'), SalesRepController.rejectProduct);
module.exports = router;
